name: Day 14 - Scheduled Log Cleanup

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM UTC
  workflow_dispatch:  # Optional manual trigger

jobs:
  clean-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build cleanup Docker image
        run: docker build -t tarundeep14/project-t-cleaner .

      - name: Run cleanup container
        run: docker run --rm tarundeep14/project-t-cleaner
