name: Day 13 - Dynamic Docker Logger

on:
  workflow_dispatch:
    inputs:
      count:
        description: 'How many log entries to write'
        required: false
        default: '5'
      message:
        description: 'Custom message'
        required: false
        default: 'Triggered log entry'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t tarundeep14/project-t-logger .

      - name: Run container with inputs
        run: |
          docker run --rm tarundeep14/project-t-logger -count ${{ github.event.inputs.count }} -message "${{ github.event.inputs.message }}"
