name: Run PowerShell Script

on:
  push:
    paths:
      - 'PowerShell/*.ps1'

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Day 4 PowerShell script
        shell: pwsh
        run: |
          cd PowerShell
          ./day4_log_writer.ps1
